"""Users table

Revision ID: 03aca8da9b4e
Revises: 
Create Date: 2025-04-02 02:39:07.120129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03aca8da9b4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cars',
    sa.Column('carid', sa.Integer(), nullable=False),
    sa.Column('numberplate', sa.String(length=32), nullable=False),
    sa.Column('rentable', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=32), nullable=False),
    sa.Column('color', sa.String(length=32), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('pictures', sa.String(length=100), nullable=False),
    sa.Column('interior', sa.String(length=32), nullable=False),
    sa.Column('bodytype', sa.String(length=32), nullable=False),
    sa.Column('gearbox', sa.String(length=32), nullable=False),
    sa.Column('doors', sa.Integer(), nullable=False),
    sa.Column('fueltype', sa.String(length=32), nullable=False),
    sa.Column('topspeed', sa.Integer(), nullable=False),
    sa.Column('power', sa.Integer(), nullable=False),
    sa.Column('torque', sa.Integer(), nullable=False),
    sa.Column('enginetype', sa.String(length=32), nullable=False),
    sa.Column('extras', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('carid')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('password_salt', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Rentals',
    sa.Column('carid', sa.Integer(), nullable=False),
    sa.Column('renterid', sa.Integer(), nullable=False),
    sa.Column('rentedat', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('rentstatus', sa.String(length=20), nullable=False),
    sa.Column('rentduration', sa.Integer(), nullable=False),
    sa.Column('rentprice', sa.Integer(), nullable=False),
    sa.Column('renteraddress', sa.String(length=100), nullable=False),
    sa.Column('renterphonenum', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['carid'], ['Cars.carid'], ),
    sa.ForeignKeyConstraint(['renterid'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('carid', 'renterid')
    )
    op.create_table('Roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id', 'role_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Roles')
    op.drop_table('Rentals')
    op.drop_table('Users')
    op.drop_table('Cars')
    # ### end Alembic commands ###
